### ISSUE TITLE
Docs redesign to handle future categories

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/openliberty.io#1023]
#887 was a temp fix.

**Comment by mdenby** [comment]
Prototypes updated:
https://ibm.invisionapp.com/share/DJNYQQP6QCM
https://ibm.invisionapp.com/share/9TNYQQRJ7A2

Putting this in the backlog for now until the Doc team decides next steps.

**Comment by mbroz2** [comment]
@mdenby moving this to the icebox.  Any work that is blocked should be in the icebox.  The backlog is only for issues that are ready for development.

**Comment by mdenby** [comment]
We'll review this next Thursday meeting in two weeks.

**Comment by steven1046** [comment]
When we get to implementing the new category design, here's a note for the developer making the changes: 
If we make a new guide with `:page-guide-category: microprofile` and don't add `:page-essential: false` it won't show up on the guides page because we check for essential: true or essential: false. We shouldn't need to put essential: false on guides that should show up in the additional guides section after the "essential" MicroProfile guides. When implementing the changes please remove this dependency as it shouldn't take long and reduce problems arising when creating more guides.

**Comment by steven1046** [comment]
Antora would allow us to put all of the TOCs for each doc type on one page.

**Comment by steven1046** [comment]
WIth the drop of Antora though, I think we will keep the current docs page for now and have those cards link to their equivalent Antora pages with respective TOC's.

**Comment by mdenby** [comment]
@mbroz2 Putting the designs here for three categories in the left and another the same but with a right sidebar option too. This also shows the rollover/active states in the navigation.

![09](https://user-images.githubusercontent.com/26823018/73485208-af059c00-4370-11ea-8bbb-c180e4c44029.jpg)
![11](https://user-images.githubusercontent.com/26823018/73485209-af059c00-4370-11ea-88d6-48ccbf73f7bb.jpg)
![10](https://user-images.githubusercontent.com/26823018/73485210-af059c00-4370-11ea-9b92-8c89a14c3bd8.jpg)

**Comment by steven1046** [comment]
This will be fixed by Antora. We will be replacing /docs/ with the entire Antora structure so all of the docs can live in the TOC and we can handle future categories/topics there.
