### ISSUE TITLE
'Contribute in GitHub' links for generated doc topics

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1085]
See https://github.com/OpenLiberty/openliberty.io/issues/1046

This issue is to cover the remaining pages/docs of ol.io not covered under #1046, that is, the generated documents that we update each release: config, features, MP APIs, Java APIs.
Before we add github links to those docs, we first have to answer the question of how we'll track those changes and contribute them back to the source so that they don't get overwritten by the docs of the subsequent release.

**Comment by NottyCode** [comment]
I don't want people to be directly editing these files, the changes need to go into the metatype. As a result I think this is very low priority unless the change in github results in the relevant metatype file being opened. The downside here is if this is done you have 4 weeks before the results get seen which sucks. 

Overall I think this should be very low priority. Note MP and Java EE API docs will have an even longer cycle time because we don't control the source and aren't the right community to do this.

**Comment by mbroz2** [comment]
Agreed that this will be low priority.  There has actually been an instance in the past where there was a bug in the MP javadoc, which we fixed locally and then submitted the same fix directly to the MP github repo so that the next time they were generated and than uploaded to the site, we'd still have the fix.

A similar pattern would need to be followed for the other docs (easier for the ones we have control over, but difficult for something like JEE APIs).

If/when we get to this issue, we should first focus on implementing this work for the docs we own, and than move on to spec APIs.
