### ISSUE TITLE
Add a way for docs to be draft and not show up on the production site

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1114]
Recently a general doc was accidentally published to the website since it was in develop on the docs repository and other things needed to be delivered. We can mitigate this by establishing a draft flag/folder for docs if they're still in development and not ready to be published.

**Comment by steven1046** [comment]
We can't use the _draft folder since that is meant for _posts that are still a draft. And using a flag would mean that it won't show up on the website but could still be crawled by Google and found by its permalink so we need another approach.

**Comment by lauracowen** [comment]
Also, I don't think it would make sense to be moving files into a _draft folder for the docs because there's a whole folder structure needed (unlike with blog posts which just go into a single folder whether it's _draft or _post).

An alternative approach would be to use a different branch (eg `docsdevelop`) and build from it to a different staging server for previewing doc content. I believe the reason that the docs have been put in the `develop` branch in the first place was so that they could be previewed on the staging server that the site infrastructure team build from `develop`.

**Comment by steven1046** [comment]
We have a drafts site, we just need to agree upon a site domain for the drafts site and also change the process to clone the new docs branch that we will use for staging instead of `develop` which will be used for QA before releasing to production.

**Comment by steven1046** [comment]
Closed because we have a draft site now.
