### ISSUE TITLE
Screen flashes white when scrolling quickly on blog

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/openliberty.io#1142]
On the blog on firefox, if you scroll down then scroll up quickly the screen flashes white for a second.

**Comment by mbroz2** [comment]
https://github.com/OpenLiberty/openliberty.io/issues/59

**Comment by steven1046** [comment]
This happens on the current guides too (in Firefox).

**Comment by mam1996** [comment]
<img width="1180" alt="Screen Shot 2019-05-28 at 1 20 47 PM" src="https://user-images.githubusercontent.com/8834112/58506863-0904f080-8156-11e9-9223-d4ccf6b02b24.png">
- Firefox Performance Screenshot

This seems to be some performance issue with how Firefox repaints the screen. It is taking around 50-90ms when scrolling quickly so it does not have a chance to draw the bg for the blog container or draw the blog posts themselves. 

<img width="824" alt="Screen Shot 2019-05-28 at 1 19 36 PM" src="https://user-images.githubusercontent.com/8834112/58506995-54b79a00-8156-11e9-9f40-d34b67410b53.png">
- Chrome Screenshot

 I went ahead and did the same for Chrome where it was working correctly to make sure that it was the performance and it appears chrome can repaint the screen while scrolling very fast.

<img width="1082" alt="Screen Shot 2019-05-28 at 2 39 33 PM" src="https://user-images.githubusercontent.com/8834112/58507037-6dc04b00-8156-11e9-842d-3f8309037bf6.png">
- Firefox 55 Performance Screenshot

I was curious and checked an older version of Firefox and found out that it was also working fine and running the paints at a fast enough pace to avoid the flash.

From this I believe that it is a bug on the painting or layering algorithm in Firefox. I have figured out a quick workaround so that the repaint issue only affects the blog posts and not the background as much by adding the following to the top of blog.css:

`html {
    background: #5E6B8D;
}`

I'll continue looking for a way to avoid this performance bug in Firefox, but I believe this is enough to show that the issue is not a bug in the openliberty.io code.
