### ISSUE TITLE
Downloads page: Update table columns (headers & values)

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1222]
For releases (https://www.openliberty.io/downloads/#runtime_releases):
Update: 
- [ ] "Newest to Oldest" to "Version"
- [ ] "Java EE profile download" to "Java EE 8"
- [ ] "Web profile download" to "Web Profile 8"
- [ ] "Full package" to "All GA Features"
- [ ] "Download all" to "ZIP"

For development builds (https://www.openliberty.io/downloads/#development_builds):
Update: 
- [ ] "Newest to Oldest" to "Build Date"
- [ ] "Tests passed" to "Tests"
- [ ] "Log details" to "Logs"
- [ ] "Full package" to "Download"
- [ ] "Download all" to "ZIP"

For Eclipse Developer Tools (https://www.openliberty.io/downloads/#eclipse_developer_tools):
Update: 
- [ ] "Newest to Oldest" to "Version"
- [ ] "Full package" to "Tools"
- [ ] "Download all" to "Download" (I think download all makes sense here since 'Tools' is plural for multiple eclipse plugins)

**Comment by barecode** [comment]
Background (for posterity) of what I had observed: The "Full package" button says "Download all". Its been a while since I went there and it makes me think that the "Download all" button means its going to download both of the other zips "javaee8.zip" and "webprofile8.zip" or something like that, but it's not that - its the zip with all of the available features. I think we should change that label to something that reflects the intent of the download, but I do not have a good recommendation on a name :)

**Comment by ellenwyllie** [comment]
Here are the final designs for the tables:

![Screen Shot 2019-08-02 at 3 03 03 PM](https://user-images.githubusercontent.com/22085207/62395715-b3bed400-b536-11e9-821a-0057b9eba793.png)

![Screen Shot 2019-08-02 at 3 04 19 PM](https://user-images.githubusercontent.com/22085207/62395766-d8b34700-b536-11e9-9c14-ecfea89768ee.png)

![Screen Shot 2019-08-02 at 3 05 10 PM](https://user-images.githubusercontent.com/22085207/62395809-f4b6e880-b536-11e9-8c12-6a2f764c9b7b.png)

**Comment by mbroz2** [comment]
"Web profile 8" should be "Web Profile 8"

**Comment by ellenwyllie** [comment]
Releases table with "Web Profile 8"
![Screen Shot 2019-08-02 at 3 30 04 PM](https://user-images.githubusercontent.com/22085207/62397090-70666480-b53a-11e9-8c40-53f84b000972.png)

**Comment by barecode** [comment]
Looks great! Very clear what my choices are and what I am downloading.
