### ISSUE TITLE
Guides--what guides should be in 'Basics' category?

### ISSUE THREAD

**Issue by mdenby** [OpenLiberty/openliberty.io#1299]
@yeekangc @lauracowen @mbroz2 @NottyCode 

I've added a 'Basics' category under Develop. 

1. Should this be a top level category or is it fine under Develop?
2. What guides should be in 'Basics'? The current four guides online are: Deploying and packaging applications, Building a web application with Gradle, Building a web application with Maven, Using Docker containers to develop microservices.
3. Where should these three guides go? Injecting dependencies into microservices, Validating constraints with microservices, Caching HTTP session data.

Here's a link to the murally board in case it's easier to work there: 
https://app.mural.co/t/olg3054/m/olg3054/1561574738608/97e509dd8f6ed69dcfff0a23190432f314049172

And here's the design again. 
![Michal's Version 01.jpg](https://images.zenhubusercontent.com/5c587f22df0733a30554ecb5/19e6901a-75b1-4216-b3cf-3c146bf862e7)

**Comment by lauracowen** [comment]
I don't think the Maven, Gradle, or Docker guides should go in the Basics category. Having them there implies that developers should do them before other guides, when that's not the case. You can do others and learn about some of the Maven/Gradle stuff in the process of doing other guides - you only need the Maven/Gradle guides for further understanding of the `pom.xml` and/or for creating your own. The Docker guide is more focused on how to set up a development environment using Docker - important and useful but not a basic starting point. I think those three guides should be in a Tools category (then any IDE guides we might produce in future can also go in there).

I think the Basics category should include 'Creating a RESTful web service' and maybe 'Consuming RESTful services with template interfaces' because they get you started with two web services that talk to each other. If you do those two guides along with the 'Deploying...' guide and maybe the 'Injecting...' guide, I think you've got the basics of writing microservices with MicroProfile on Open Liberty.

'Validating constraints' and 'Caching HTTP' shouldn't be in Basics. I'm not sure which they should be in though.

I don't think we can have a Basics category that is mutually exclusive from other categories. It cuts across other categories so the guides in the Basics category would need to be in more than one category. Otherwise (assuming my Basics category above), developers coming looking for guides about, say, MicroProfile client, wouldn't find it in the Client Side category because it's in the Basics category.

**Comment by yeekangc** [comment]
For a Basics or Essentials category, in my mind, we should have "Packaging and deploying applications" (i.e. Getting Started), "Injecting dependencies" (i.e. CDI), and possibly MP Config guides.

**Comment by mdenby** [comment]
Based on the last meeting we said that these two guides are basics:

1. Deploying and packaging applications
2. Injecting dependencies into microservices

Closing this issue.
