### ISSUE TITLE
Improve site visibility of Maven/Gradle/Developer Tools

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/openliberty.io#136]
The site should provide more access points to getting started with OpenLiberty aside from downloading as a zip. Specifically, we want to improve the visibility of Liberty Maven and Gradle plugins, and other tools surrounding the developer ecosystem.

The Liberty integration team has some ideas for improvements in this area:

1. On the homepage, add links to OpenLiberty Maven/Gradle artifacts next to or below the zip download button.
2. On the homepage under "Get started," add separate instructions to build the `sample.mpconf` project using Gradle, and corresponding links to the Getting Started guides for Maven and Gradle. 
3. Create a developer "ecosystem" landing page (accessible through the top navigation menu) with links to our Getting Started guides for Maven and Gradle, `ci.maven`/`ci.gradle`/`ci.ant` source and documentation, Eclipse developer tools, app accelerator, and other tools surrounding the OpenLiberty ecosystem.

**Comment by lauracowen** [comment]
These are useful suggestions so I'm going to attempt to re-write them in terms of the requirements we may need to address rather than specific implementation requests. Please review and respond if you feel I've not captured the requirements correctly.

----

There's currently work being done (by me, @gcharters, @cajaygle, @NottyCode, and others) to design a 'Getting Started' experience (or set of experiences) for developers new to Open Liberty. The existing experience is that developers are presented with a Download button but no other guidance as to what to do with the server they've downloaded or how to use it to create an app. The early definition of the new GS experience is to use Maven (I don't know about Gradle yet - I think the aim is to deliver a simple experience using Maven for a start rather than try to cover everything at once). As part of the work, there will be consideration given to how and where this GS experience will be presented to visitors to the OL.io website, including how it's presented relative to the current Download button on the homepage. I don't have any more relevant (to this issue) detail about the GS design than that yet though and nothing to show for feedback yet unfortunately.

Regarding the specific suggestions in this issue:

1. How to present the GS experience (and what it is) is something that is currently being looked at (see above).

2. There is also work going on (separately) with the `sample.mpconf` sample on the homepage (I'm not sure exactly what though so talk to @gcharters for more info). How it's presented on the home page will also be discussed as part of the overall Getting Started experience of Open Liberty (again, see above).

For both of these, the important thing is how Maven and Gradle fit into the experience of developers (and devops) using Open Liberty and what's the best way for them to successfully write and deploy their apps using Open Liberty (which is their goal in trying Open Liberty and which is what the work on the Getting Stared experience and design of the homepage is attempting to address).

3. How we handle 'ecosystem' tools etc around Open Liberty is something yet to be decided - could you create a separate issue for this, please? It's an important area of information/documentation needed and we need to consider it more and is separate from the 'getting started' concerns of the other two points. Also, I think that 'ecosystem' might be a bit vague as a categorisation and I think we'd need to consider all the types of tools/software that fall under that description and how developers coming to the site will expect to find them.

Hope all that makes sense. My brain is now melted and needs a weekend.

**Comment by yeekangc** [comment]
@cajaygle @megmulsy, any thoughts on this issue and moving forward with it?  Thanks.

**Comment by lauracowen** [comment]
Discussed on design call. It's maybe more a case of making Maven/Gradle/Docker more visible on the OL.io Downloads page. When we point people to the Downloads page to say we have a new version out, it looks like we're expecting them to download and install old-school-style when, actually, we have Maven, Gradle, Docker support.

Maybe we should present the Maven and Gradle coordinates and Docker command on the Downloads page at the top and then "if you want the download package, here it is..." beneath that.

Maven/Gradle/Docker example (slightly out-of-date) is shown here: https://openliberty.io/blog/2018/12/14/microprofile21-18004.html
