### ISSUE TITLE
Use Jekyll's _drafts folder

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#137]
Let us try using the builtin `_drafts` folder and `--drafts` flag to stage upcoming blog posts.

https://jekyllrb.com/docs/drafts/

**Comment by kinueng** [comment]
Hi @lauracowen,
The new `_drafts` folder is now in our `development` branch.  I put an example asciidoc in the `_drafts` folder as a starter.  

See the draft blog here:
https://openlibertydev.mybluemix.net/blog/

**Comment by lauracowen** [comment]
Cool! So this is how I understand it....

I can merge people's draft blog posts to `development` branch and they'll get automatically built to the test server? We can modify the blog post until it's ready to publish. Then, when I want to publish it, I move it out of the `_drafts` folder and do a PR to Master.

In the meantime, if the `_drafts` folder and contents gets merged to `master` (because other code in that `development` branch is being merged to `master`), it'll just get ignored by the production build.

**Comment by kinueng** [comment]
Hi @lauracowen,

> I can merge people's draft blog posts to development branch and they'll get automatically built to the test server?

Correct. The draft blogs will only show up on openlibertydev.mybluemix.net.

> Then, when I want to publish it, I move it out of the _drafts folder and do a PR to Master.

Correct.  The move out of `_drafts` folder will would give us a change to rename the Asciidoc file with a release date.

> In the meantime, if the _drafts folder and contents gets merged to master (because other code in that development branch is being merged to master), it'll just get ignored by the production build.

Correct.  The `_drafts` folder support is now in openliberty.io and the asciidoc file in `_drafts` is missing as expected.
