### ISSUE TITLE
Basic starter on downloads page

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1424]
Provide a basic starter for OL allowing them to choose between various specs (MP & Jakarta) & build automaton systems (gradle & maven).

This section would be at the top of /downloads and would end up providing the user a link/download of a zip which would have the minimal content for them to get started (pom.xml/build.gradle, server.xml, and, perhaps, a sample app with tests).

Should this also include an option for generating/providing a DOCKERFILE?

The design should take into consideration that this will likely expand in the future to include more specs/technologies & provide finer grain choices (subsets of technologies).

Design presentation: https://ibm.box.com/s/fqf5hnscl1vildehcpnsx5aeqdbkr732

**Comment by mdenby** [comment]
@mbroz2 I think we can close this one?

**Comment by mbroz2** [comment]
@mdenby we still want to pursue this work.

**Comment by k8vance88** [comment]
See https://github.com/OpenLiberty/open-liberty/issues/12373

**Comment by mdenby** [comment]
![USE THIS ONE Copy 2](https://user-images.githubusercontent.com/26823018/96268023-8709a780-0f96-11eb-80cc-5b102008cc8b.png)
[Redlines--Get Started Page.zip](https://github.com/OpenLiberty/openliberty.io/files/5392150/Redlines--Get.Started.Page.zip)

**Comment by mdenby** [comment]
@mbroz2 Here are a bunch of versions

1. With the drop down as a label
![USE THIS ONE v1](https://user-images.githubusercontent.com/26823018/96905639-b91f7b80-1466-11eb-94e0-a4c6680f9301.png)

2. The version number only in the drop down
![USE THIS ONE v2](https://user-images.githubusercontent.com/26823018/96905695-cc324b80-1466-11eb-9e14-d4b0c2b9e348.png)

3. Another option having the version in a drop down. This one mirrors how we handle versions in Docs.
![USE THIS ONE v3](https://user-images.githubusercontent.com/26823018/96905789-ec620a80-1466-11eb-8a7d-9a6f22cff164.png)

4. Labels at the top above the version drop down. (May be my new favorite)
![USE THIS ONE v4](https://user-images.githubusercontent.com/26823018/96905877-069be880-1467-11eb-8c97-ae4fcf97bb81.png)

**Comment by mdenby** [comment]
And what would that look like with more items you asked? Like this! The same as above but with more items.

![USE THIS ONE v1 Copy](https://user-images.githubusercontent.com/26823018/96906007-377c1d80-1467-11eb-80f9-39540b21f8c4.png)
![USE THIS ONE v2 Copy](https://user-images.githubusercontent.com/26823018/96906008-3814b400-1467-11eb-999f-9d095d36be2f.png)
![USE THIS ONE v3 Copy](https://user-images.githubusercontent.com/26823018/96906010-3814b400-1467-11eb-9402-6c08c21d9e56.png)
![USE THIS ONE v4 Copy](https://user-images.githubusercontent.com/26823018/96906013-38ad4a80-1467-11eb-8367-efaf9e41c0ca.png)

**Comment by mbroz2** [comment]
Great ty!  Of those, my preference is 2 followed by 1.  My issue with 3 & 4 is that they're repetitive, and what they repeat ("Version") is not important.  
Perhaps if had an option like 4, but with the dropdown only containing the numerical version (avoiding the repetitive "Version"), like the dropdown in 2, that could make for a good option.

**Comment by k8vance88** [comment]
Number 2 is what I had pictured in my mind after the call.  However, the labels above the fields looks good to me. It's more in line with what we see in the first two fields (Application name and Package).

**Comment by mdenby** [comment]
I like 4 because it's neater and consistent with space, easier for spacing, and even though no one likes the "version" repeated it does match our version picker in docs.

**Comment by yeekangc** [comment]
Any thoughts on which option will work better for accessibility?

**Comment by k8vance88** [comment]
Options 2-4 should not have accessibility issues. Option 1 does because it doesn't provide a visible label for the fields.  (After you make a selection, context could be lost)

**Comment by yeekangc** [comment]
Thanks!  I was thinking 1 may not work.  In that case, I lean toward 4 then 3 and lastly 2.

Yes, we are repeating "Version" with 4 but the label are consistent in how they are placed and they are all nouns (besides what Melissa and Katie mentioned).  Looks clean to me too.

**Comment by mbroz2** [comment]
If there's no a11y issues with option 1, then go with that, otherwise option 2 with no "version" (either way, don't bother with "version"..... which really is driven by the backend api response and not the design)

**Comment by mdenby** [comment]
Adding the redlines of option 1 and option 2 here.

[Option 01 redlines.zip](https://github.com/OpenLiberty/openliberty.io/files/5532344/Option.01.redlines.zip)
[Option 02 redlines.zip](https://github.com/OpenLiberty/openliberty.io/files/5532346/Option.02.redlines.zip)

**Comment by steven1046** [comment]
Browsers implement their own radio button styles, if we want to use a black radio button for Maven/Gradle then we would need images for the unselected and selected versions of those @mdenby.

**Comment by steven1046** [comment]
Based on the last website call we need:
1. A way to mark that a field is invalid and needs to be corrected before submitting
- Maybe add an icon next to the field because changing the label to red text would probably not pass accessibilty requirements with the green. 
2. If the user changes the Jakarta EE version and we automatically update their MicroProfile version choice to the highest one that's valid with their Jakarta EE version, then we need some sort of message design saying we updated them to a valid set of options.
3. A design for a disabled 'Generate Project' button when the form is not ready

**Comment by steven1046** [comment]
@mdenby are you able to create design changes for the above?

**Comment by mdenby** [comment]
Yes, I can work on this.
 
----- Original message -----From: Steven Zvonek ***@***.***>To: "OpenLiberty/openliberty.io" ***@***.***>Cc: mdenby ***@***.***>, Mention ***@***.***>Subject: [EXTERNAL] Re: [OpenLiberty/openliberty.io] Basic starter on downloads page (#1424)Date: Wed, Jun 16, 2021 3:10 PM      @mdenby are you able to create design changes for the above? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
@mdenby are you able to create design changes for the above?

**Comment by mdenby** [comment]
New screens. I wonder if @lauracowen needs to review my wording on the notification and error messages. For the error message I put two options:

1. "Please enter a valid application name." or "Please enter a valid base package name."
2. "Valid characters include A-z, 0-9, and (.  _ –)" The idea here is to let the user know what characters to use instead of just telling them what they entered was incorrect.

![Final empty state](https://user-images.githubusercontent.com/26823018/122679327-6befd700-d1b8-11eb-8f9d-a22a4ccf2b7c.png)
![Final select version](https://user-images.githubusercontent.com/26823018/122679330-6d210400-d1b8-11eb-820b-b0b96f25f7b4.png)
![Final error](https://user-images.githubusercontent.com/26823018/122679331-6db99a80-d1b8-11eb-8be1-f5cda2067585.png)
![Final notification](https://user-images.githubusercontent.com/26823018/122679332-6e523100-d1b8-11eb-91fa-3ad3929a2dcd.png)

**Comment by mdenby** [comment]
Oh, also do I need to make the mobile version showing the form?

**Comment by steven1046** [comment]
It should look roughly the same in mobile, but the fields would be stacked because there's not enough space right?

**Comment by mdenby** [comment]
Yes, exactly. I just didn't know if redlines were needed to show that or not. If so, I'm happy to make them.

**Comment by steven1046** [comment]
That would be great! Just to clarify the spacing and the size of the warning label. I don't think anyone would be downloading a starter on a mobile device, but if their screen size is small enough then it would show the mobile view.

**Comment by mdenby** [comment]
Adding the redlines for mobile etc here...along with the error, empty, and notification screens.

[Get Started form Redlines.zip](https://github.com/OpenLiberty/openliberty.io/files/6765594/Get.Started.form.Redlines.zip)
