### ISSUE TITLE
Using Asciidoc Callouts for Hotspots

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#1474]
Investigate and design the use of callouts to improve how we show and how users work with hotspots in the guides.  This involves UI design, website implementation as well as handling within the guides (Asciidoc) themselves.

https://asciidoctor.org/docs/user-manual/#callouts
https://mrhaki.blogspot.com/2019/12/awesome-asciidoctor-auto-number-callouts.html?m=1

@mdenby @mbroz2 @steven1046 @gkwan-ibm @lauracowen

**Comment by mbroz2** [comment]
This is supported on docs; guides use their own 'callout' system.

**Comment by yeekangc** [comment]
We will revisit when we have user feedback and a need to revise the design for this.

**Comment by steven1046** [comment]
Perhaps having the callouts and hotspot hover behavior, placing the callouts inside of the gray block that you can hover over to highlight the lines of code. This might help the user know that they can hover over the hotspots and also that it relates to the code, because the callouts will be in both the text and code.

**Comment by yeekangc** [comment]
Some recent guides started to have more hot spots around text in the guides vs technical keywords alone:

https://github.com/OpenLiberty/draft-guide-cloud-openshift-operator
https://github.com/OpenLiberty/draft-guide-mongodb

Not saying this is the way to go but there may be cases where hot spots on text in the guides is easier and better for the users and having a design with callouts may provide a better solution and experience.  (Currently, the hotspots on keywords and text look the same, which get very confusing.)

**Comment by lauracowen** [comment]
@yeekangc I asked the authors to fix this in the social media login guide because the 'hotspots' were being used as a way to indicate stuff in the code in the way you might have hyperlinks in text, rather than in highlighting the location of specific technical keywords in the code. In practice, it didn't even require callouts because it just required the text to be re-written to include the technical keyword that was required. I'd rather not introduce the use of callouts as well if we can help it (unless there's really clear use cases for them) as it gets more complicated and we'll end up with some guides using one or the other based on the preference of the author rather than the requirement of the guide.

In most cases where a guide isn't following some format/style/syntax guidance properly, it's usually because the text needs re-writing, I've found. When that doesn't apply, it's clearly an exception that is justified but which should only occur very occasionally. For example, the concept of editing a line in a file instead of creating a whole file is rarely justified; only when the scenario makes sense such as demonstrating how to change an app from one technology to another; most of the time it's just that the author hasn't understood/known the reasoning for behind the style guidance or needs to re-structure/re-word the text.

**Comment by yeekangc** [comment]
I agree and thank you, @lauracowen.  The recent cases are examples where we need revisions.

Wanted to note what came up in case we need to revisit this (i.e. the potential use of callouts) down the road.
