### ISSUE TITLE
Add Open Liberty API & SPI Javadocs

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1550]
Currently we only publish Javadocs for MP & JEE; also publish Open Liberty API & SPI Javadocs.

**Comment by dmuelle** [comment]
@hlhoots has been working on this and provided this OL javadoc jar, based on the WebSphere Liberty javadoc. Can we look into adding this to draft to see how it works?

[com.ibm.openliberty.javadoc.zip](https://github.com/OpenLiberty/openliberty.io/files/9473435/com.ibm.openliberty.javadoc.zip)

**Comment by kinueng** [comment]
The documentation in the jar in https://github.com/OpenLiberty/openliberty.io/issues/1550#issuecomment-1234785822 is not formatted in a way where it can be dropped into openliberty.io. There will need to be work in the generation code.

From my recollection, the jar is formatted like these docs here https://www.ibm.com/docs/en/was-liberty/nd?topic=SSAW57_liberty/com.ibm.websphere.javadoc.liberty.doc/api_ndz.htm

**Comment by hlhoots** [comment]
@kinueng The link you pasted on the comment above - where does that content come from?

**Comment by dmuelle** [comment]
Hi @hlhoots those HTML files are generated with the Liberty GM build for each release. I get them from [a link that @samwatibm posts to #was-dev-announcements monthly ](https://ibm-cloud.slack.com/archives/C03HP6CHPPD/p1670344740902969). Here's where I got the files for 22.0.0.13:
https://rtpgsa.ibm.com/gsa/rtpgsa/projects/l/liberty.shipped/liberty/WASX.LIBERTY/shipped/cl221320221205-1900.59.linux/linux/zipper/externals/installables/

On that page, the link for [com.ibm.websphere.javadoc.liberty.doc.jar](https://rtpgsa.ibm.com/gsa/rtpgsa/projects/l/liberty.shipped/liberty/WASX.LIBERTY/shipped/cl221320221205-1900.59.linux/linux/zipper/externals/installables/com.ibm.websphere.javadoc.liberty.doc.jar) downloads the JAR of html files for the javadoc, which I then manually upload to IBM Docs cloud object storage. 

note that this same folder contains the [com.ibm.openliberty.javadoc.doc.jar](https://rtpgsa.ibm.com/gsa/rtpgsa/projects/l/liberty.shipped/liberty/WASX.LIBERTY/shipped/cl221320221205-1900.59.linux/linux/zipper/externals/installables/com.ibm.openliberty.javadoc.doc.jar) that you recently produced as a test case.

**Comment by kinueng** [comment]
Shared with @hlhoots how the current javadocs are generated on openliberty.io in hopes it helps with generating the Open Liberty API and SPI javadocs.

**Comment by steven1046** [comment]
The implications of removing frames for the javadocs on the website is that we would:
1. Lose frames, which is supported by the search box on the javadocs which works pretty well and is what I would use when looking up a method/class myself.
2. We would need to modify our https://github.com/OpenLiberty/openliberty.io/blob/prod/src/main/content/antora_ui/src/js/06-javadocs.js javascript for javadocs on the site, to not parse the packages and class frames which we do to add accessibility fixes and hiding the footer.
3. Would need to add javascript/redirect code to handle the current query parameters for classes and packages in urls to navigate to the correct spot in frameless javadocs which don't have the context in query params.
4. Changing the website to frameless javadocs would help host the Liberty API and SPI javadocs which we already have generated.
5. We have a lot of redirect code to handle query parameters from pre-Antora to post-Antora that would need to be modified if we remove frames on older javadocs.

If we don't remove frames, the current Open Liberty API and SPI javadocs would not work so well with the website, because there is a separate html landing page for each Java class instead of one TOC.

Overall, i would advocate for switching to frameless javadocs because that is what newer versions of Java are moving towards.

The question would be if we want to remove frames on existing javadocs on the site so they are consistent.
