### ISSUE TITLE
Scroll Nav-bar jump

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/openliberty.io#1640]
For me, regardless of which browser I use, when I scroll up and down the page the current section highlighted on the side nav-bar, and the files being displayed, jump around in a random order.

When scrolling from top to bottom, the highlighted sections are as follows:

1. Close the table of contents
2. Contents
3. What you'll learn
4. Background concepts
5. Example: DevOps pipeline
6. **Injecting configuration through @ConfigProperty annotation**
7. **Enabling MicroProfile Config in Open Liberty**
8. Providing optional default values
9. Configuring with the properties file
10. **Providing optional default values**
11. Configuring with an environment variable
12. **Configuring with the properties file**
13. ...
13. The rest seem fine

Since the demo depends on showing how the user is interacting with the 'sandbox', this bug makes the guide very difficult to use.

I have tried using both Google Chrome and Firefox.

My `styles` tab of my browser shows a window resolution of: 2993 x 10640

**Comment by steven1046** [comment]
This page seems to do the section detection well: https://reactjs.org/tutorial/tutorial.html. It looks like when scrolling down it keeps it on a certain section *until*  the next section is a certain distance from the top. When scrolling up, it goes to the previous section when a certain amount of it is into view it looks like. We could implement something similar and then let guide authors test it out on a demo site to see if it's what we want. There is no perfect solution since sometimes a guide author might want a section to switch sooner or to switch later, so as long as it works in most cases then we could use this method.

**Comment by Joseph-Cass** [comment]
I don't know if this is associated with this fix, but the guides now have huge gaps for me (see attached).

If you don't think it's associated @steven1046 I'll open a new issue.

![image](https://user-images.githubusercontent.com/55994281/86573635-92e3d780-bf6c-11ea-8a91-d534a658f57b.png)

**Comment by steven1046** [comment]
This is intended by design, see #1693. You can add to that issue if you think it should be changed!
