### ISSUE TITLE
Server Config breadcrumb shouldn't load on the overview

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1837]
https://openliberty.io/docs/20.0.0.9/reference/config/server-configuration-overview.html#server-env loads a breadcrumb but doesn't have sections so it just shows the title the whole time. We should disable the breadcrumb from loading on this page.
Note, it is only loading the breadcrumb if you come to the overview page with a hash in the URL.

**Comment by steven1046** [comment]
![image](https://user-images.githubusercontent.com/6392944/91731901-171d9a00-eb6d-11ea-9d95-42dfe7b1dad6.png)

**Comment by steven1046** [comment]
This happens on config pages that also don't have a breadcrumb, if you add a hash onto the url. Let's fix it for all of the pages if there shouldn't be a breadcrumb. Edit: only fix on other pages if we're certain that we can determine if a hash is invalid or not.

**Comment by natalie-bernhard** [comment]
I added a specific fix in the config JS for this page since it seems to be the only page that behaves this way.  Are there any other pages that should be included in this? I could not replicate this behavior so far in any other documentation, even with the same page and anchor on other versions of the docs or with different anchors on the page linked to in the initial issue.

**Comment by steven1046** [comment]
This problem is only in the config overview, so that makes sense!
