### ISSUE TITLE
Doc table bottom border extends past edge of table

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/openliberty.io#1866]
I noticed that in the [External Configuration of Microservices doc](https://openliberty.io/docs/20.0.0.9/external-configuration.html#_default_configsources), the bottom border of the table extends too far to the right. I wasn't able to find this issue in any other doc tables and I think it's just because this table isn't as wide as the others.
![Screen Shot 2020-09-10 at 9.16.23 AM.png](https://images.zenhubusercontent.com/5ba54aeed542104d81ce6b5c/c31de030-f21b-4905-b60d-1db8bbc8919f)

**Comment by dmorgant** [comment]
The `display:block` in the following css is causing the table to start on a new line and take up the whole width.

In antora_ui/src/css/doc.css
```
.doc table.tableblock {
    border-collapse: collapse;
    font-size: .83333rem;
    margin: 2rem 0;
    display: block;
    overflow-x: auto;
}
```

Allowing it to default to `display:table` works, but the width is wrong (extends the width of the container) because of the table styling in antora_ui/src/css/config.css
```
table {
    margin-top: 30px;
    margin-bottom: 54px;
    margin-left: -20px;
    -webkit-box-shadow: 0 4px #d6d9e4;
    box-shadow: 0 4px #d6d9e4;
    width: calc(100% + 20px);
}
```
Will have to look into why the width is set up this way.

**Comment by dmorgant** [comment]
Here is what I have determined:
- There are numerous tables that are seeing the formatting error described in this issue where the bottom border of the table extends too far to the right.

![image](https://user-images.githubusercontent.com/29490139/113175371-f9063e00-9210-11eb-90cf-23c01d9b2e87.png)

To recreate, it really is just a matter of finding a table with limited content so that the table fits within the width of the content area without any of the data within any of the columns flowing to another line within any of the table cells.  This is easily seen in the [JMX metrics reference list](https://openliberty.io/docs/21.0.0.3/jmx-metrics-list.html) document.

At the following snapshots width, all the data in all the table cells fit on one line so the area needed to display the table is smaller than the window width. But the table is configured to have a width of (100% + 20px) and the bottom border of the table appears to extend too far to the right.

![image](https://user-images.githubusercontent.com/29490139/113178576-58198200-9214-11eb-92af-4e266811b645.png)

But, making the browser window smaller in width, some of the data in the table cells flow to another line and the bottom border of the table appears to end where expected.

![image](https://user-images.githubusercontent.com/29490139/113178753-7ed7b880-9214-11eb-8a89-71696df7fe32.png)

What we would like to see is for each cell in the table to expand to take up the configured width for the table (100% + 20px): 

![image](https://user-images.githubusercontent.com/29490139/113178668-6bc4e880-9214-11eb-9b8d-fa8bd40b9cf2.png)

When the table is configured so that its `display` is set to `table` this occurs.   However, our tables are configured to have `display` set to `block`......

- The code causing the issue is in antora_ui/src/css/doc.css.   In this css entry, `display` is set to `block`.
```
.doc table.tableblock {
    border-collapse: collapse;
    font-size: .83333rem;
    margin: 2rem 0;
    display: block;
    overflow-x: auto;
}
```
If we comment this out the `display` defaults to `table` and the extended bottom border on the smaller tables goes away.  All tables now fill the table's configured width (100% + 20px)!

The code for `display: block` was added to the CSS file with https://github.com/OpenLiberty/openliberty.io/pull/1741.  It just says that it was done to 'Prevent overflow to the right side of the page when there is a long table.'   But does it really? ....

- On some of our tables, there are columns which have cell content that cannot be wrapped to multiple lines. Therefore, as the browser window width is made smaller, the cell width hits a minimum where it will not be made any slimmer.  At these times, a horizontal scrollbar appears.  Now, with `display: block` the scrollbar is appearing right underneath the table as can be seen in the table for [Metrics reference list](https://openliberty.io/docs/21.0.0.3/metrics-list.html)
  
![image](https://user-images.githubusercontent.com/29490139/113190035-818cda80-9221-11eb-9c53-3a6840e71881.png)

If we were to convert to `display: table` the horizontal scrollbar would appear on the page itself:

![image](https://user-images.githubusercontent.com/29490139/113190450-e9dbbc00-9221-11eb-8816-b43c552c6b5a.png)

Is that what we were trying to avoid with the change to the CSS in issue #1741?   I personally find it more usable to have the scrollbar appear on the page so you can easily scroll when you come across the table to see all the headings and not have to scroll to the bottom of the table to get to the scrollbar and then move back to the top to see the headings and then move back to the bottom to scroll left... and then....you get the picture.

- With the CSS set to `display: table`, we can still have the scrollbar directly underneath the table.   It requires adding a `<div>` with `overflow-x` set to `auto` **around** the table.   Then a horizontally overflowed table would get a horizontal scrollbar because of the encasing div.   At this time, I do not know how this would be done with the conversion from asciidoc.

- I did check with how the tables were defined in the different docs.   While some were defined like:
```
[%header,cols="9,9,2,9,9,2"]
```
others were defined specifically specifying that the table should take up 100% like:
```
[cols="a,a,a,a",width="100%"]
```
The problem with the bottom border of the table extending too far to the right occurred with either kind.  So, setting `width="100%"` didn't make a difference.

- Anyone know why the table width is set to be `(100% + 20px)` in antora_ui/src/css/config.css?
```
table {
    margin-top: 30px;
    margin-bottom: 54px;
    margin-left: -20px;
    -webkit-box-shadow: 0 4px #d6d9e4;
    box-shadow: 0 4px #d6d9e4;
    width: calc(100% + 20px);
}
```
______________________________________________________________

@steven1046 @k8vance88

To summarize.....I think this issue is more prevalent than initially thought.   Just go to Reference->Server Config and you'll see quite a few tables in those docs and depending on your browser width many of them will have the extended bottom border.

I also think we should go back to configuring the tables to be `display: table` rather than `block` and let the scrollbar appear on the page for the very few tables that are quite wide and can't get any slimmer because of their content.     Currently (I have not tested **EVERY**thing), I only see this with the [Metrics reference list](https://openliberty.io/docs/21.0.0.3/metrics-list.html) and the [Differences between MicroProfile Metrics 1.x and 2.0](https://openliberty.io/docs/21.0.0.3/reference/metrics-1-dif.html) docs.

I also think we should go back to just `100%` width, and not the `(100% + 20px)`.   Thoughts?

**Comment by dmorgant** [comment]
Steven and I discussed this issue and decided to remove the formatting of `display: block` for `<table>` elements, allowing them to revert to `display: table` where the cells were more accurately being stretched to 100% of the table width.  Also, we decided to set the table width at 100% instead of the (100% + 20px) which was causing unnecessary horizontal scrolling at some browser window widths on pages containing tables since it allowed the table to extend past the content width.

See PR #2073

**Comment by dmorgant** [comment]
Differences between `display:table` and `display: block`:


Both `display: block` and `display: table` won't display next to anything else, by default. The biggest difference is that `display: block` will extend to 100% of the available space, while `display: table` will only be as wide as its contents unless a specific width is otherwise set (more on that later). Also, `display: table` is required to get `display: table-cell` or other table- stuff to work in the descendents (`<tr>, <td>, <thead>, <tbody>, etc).
