### ISSUE TITLE
Pre-populate issue information when a user clicks Open Issue from a docs page

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/openliberty.io#1914]
If someone clicks the **Open Issue** link from a docs page, can we pre-populate information for them so that they don't have to go back and copy the file name and link to the topic that they're raising an issue about? Some info about how to do this may be found at https://github.com/isaacs/github/issues/99.

**Comment by steven1046** [comment]
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters

**Comment by k8vance88** [comment]
Investigate using a template to pre-populate some of the fields, as well as provide specific information via query parameters

**Comment by mbroz2** [comment]
Github allows us to pass various fields like title, body, label and template via query paramenters, so we can use that to prepopulate the issue

**Comment by natalie-bernhard** [comment]
Here is the information that I had the issue populate with based on the original description above.  Is there any other information that should be populated?  The only other thing I can think of would be to add a space labeled "Description:" for the user to describe in detail the issue with the documentation.  I wasn't sure if title should be populated since titles are usually more specific about what the actual problem is with the documentation.
Below are both the Write and Preview tabs for the issue. The link becomes active when the issue is submitted as seen in the Preview tab
![Screen Shot 2021-06-01 at 4 56 17 PM](https://user-images.githubusercontent.com/84740311/120390069-42e7cf00-c2fb-11eb-9bb5-1480bee4e622.png)
![Screen Shot 2021-06-01 at 4 56 32 PM](https://user-images.githubusercontent.com/84740311/120390072-44b19280-c2fb-11eb-9fb5-338f854bd91c.png)

.

**Comment by steven1046** [comment]
@dmuelle do you have any feedback on the above?

**Comment by dmuelle** [comment]
I think this looks great. If we want to add some sort of description prompt, could be something like

"Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it."

That might be overkill :) But sometimes outside users open docs issues that are really either issues with their own app/environment or with the code itself and not the doc. The more info we have up front, the quicker we can get them to a solution, whether through the docs, opening a bug in the main repo, or pointing them to support.
