### ISSUE TITLE
The right code pane cannot show "\\s+" string correctly for java file

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#1975]
Personal development site lgdev can show `"\\s+"` string in java file at the right code pane but qa site show `"\s+"` (missing a slash character)
- from  https://github.com/OpenLiberty/guide-microprofile-metrics/issues/91

**Comment by steven1046** [comment]
I think we found out that this is due to the `minify_html: true` set in the configy.yml jekyll config, whereas in your dev environment you have `minify_html: false` set, right @gkwan-ibm?

**Comment by gkwan-ibm** [comment]
probably yes, lgdev set `minify_html: false`

**Comment by mbroz2** [comment]
Looks like the issue is in the minifier (https://github.com/octopress/minify-html) but unfortunately it doesn't seem like it's being actively maintained anymore (though we can certainly try and open an issue).
We're also looking at switching to a different minifier (#742 ) which may resolve this issue.

In the meantime, I suggest changing the example/test code to avoid this scenario.
