### ISSUE TITLE
Add GA event for clicking 'copy' button on github clone step in guide

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2008]
When a user click the 'copy code block' button for cloning the guide repo in the Getting Started step, send an event to GA.
![image](https://user-images.githubusercontent.com/3076261/104747405-1baaaf80-5716-11eb-9bd1-5afa31edf835.png)

**Comment by steven1046** [comment]
GA = Google Analytics

**Comment by dmorgant** [comment]
I need more information on the eventCategory, eventAction, etc., or am I to create new ones for this button?

**Comment by dmorgant** [comment]
Discussed this issue with Michal and he proposed something like

> Event Label should be the url, like /guides/getting-started.html (though that might happen automatically, not sure)
> Event Category: "Guide Clone"
> Event Action: "Copy"

**Comment by dmorgant** [comment]
Information collected:

The copy clipboard icon appears as a user mouseenters a section.  It appears EVERYwhere there is a section of commands or code to be copied.  It appears in static guides, interactive guides, docs, site content, etc..  

This issue is with respect to the static guides only.   The interactive guides do not have the same section within the guide content to download the guide sample.....although you can download the sample app at the end...but it is not needed to go through the guide so it is not part of this issue.  The code that makes the copy clipboard icon appear for static guides is in js/guide-static.js.  Search for '`#copy_to_clipboard`' to find the code that positions the icon in the correct section when a mouseenter event occurs, removes it on mouseleave, and its onclick handler.

The `#copy_to_clipboard` icon is an image that is inserted at the end of the `#guide_column` following `#guide_content`.   It initially is styled with 'display: none` so it is hidden.  When a user mouse enters a section, it is absolutely positioned into the correct section.

I believe the code to Google Analytics (GA) will go into guide-static.js in the onclick handler for `#copy_to_clipboard`.  We can look at the `target.innerText` to determine if the target section contains the text `git clone`, which is the only section we want the event to trigger GA.

There is a GA event made when the user selects one of the guide review icons at the bottom of each guide (the smiley/frowning faces).  You can find this on the onclick handler in js/guide-common.js in addGuideRatingsListener().  
>        if(typeof ga === "function"){
>            ga(1, "Guide Review", rating, 3);
>        }


I was unable to complete this issue because I did not have access to the Google Tag Manager to set up the new event.  You also need access to Google Analytics to verify it works.

**Comment by steven1046** [comment]
The button can be tracked in Google Analytics, but we need to add an id or class to the little icon that pops up when you hover over it, so GA has a way of telling it was the copy to clipboard `for the git clone code block`.
