### ISSUE TITLE
Implement caching & fix docs-generated content for noversion page

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#2226]
Use caching in order to reduce requests made to Github API needed for this functionality in order to make it less likely to reach rate limit

**Comment by mbroz2** [comment]
Should we instead asynchronously just call our server for each file for an existing version of docs and see if it returns 202 or 404?
This would avoid any issues with regards to being limited by github APIs rate limits.

For the short term, suggest doing HEAD request (so as to not actually request a file), if one comes back as a 404, abandon waiting for anything older.
The better solution would be to create a backend API to provide this info, whos content would be generated at build time.  We could see if we could generate the antora sitemap (https://docs.antora.org/antora/2.3/run-antora/) and then query for it and loop through it to get all the available versions for a doc.

**Comment by mbroz2** [comment]
Also as part of this, fix the issue where content from docs-generated (features, config, commands, etc) do not get versions listed because currently only the `docs` repo is searched.  I think the previous comment would naturally solve this without any extra work, but it should be verified that it does.
