### ISSUE TITLE
Change guide skills network label for analytics from url randomized id to the title of the landing page

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2302]

**Comment by steven1046** [comment]
Add `guide-name` to the query parameters too

**Comment by kinueng** [comment]
A skill network URL example showing the randomization data https://ol-staging.skillsnetwork.site/courses/course-v1:IBM+GPXX0G3KEN+v1/auto_enroll?next=/courses/course-v1:IBM+GPXX0G3KEN+v1/courseware/guided_project/guided_project

One suggested approach is to add an additional query parameter, like `guide-name=<guide title>` so that the analytics data can show some human understandable data.  The data will still have the random URL, but will have the additional `guide-name` in the URL to help understanding the data.

**Comment by kinueng** [comment]
It was discovered that the suggestion in https://github.com/OpenLiberty/openliberty.io/issues/2302#issuecomment-988954339 will not work.

Additionally, the guides team indicated that they have a custom tool to map the randomized id to a guide title.  Given they have a custom tool, is this work item still needed?

**Comment by kinueng** [comment]
Additional details:

> By adding queryParams https://ol-staging.skillsnetwork.site/courses/course-v1:IBM+GPXX04TNEN+v1/auto_enroll?next=[…]ided_project/guided_project&guide-name=getting-started and we redirect to analytics page actually it removes queryParam and it shows only https://courses.ol-staging.skillsnetwork.site/courses/course-v1:IBM+GPXX04TNEN+v1/courseware/guided_project/guided_project/

**Comment by kinueng** [comment]
The guides team is in agreement to go ahead and close this issue for now.  If there are gaps that need to be closed in this area, we can revisit this issue.
