### ISSUE TITLE
docs/*/reference/config/application.html fails ZScaler scan with Trojan error

### ISSUE THREAD

**Issue by vickimfox** [OpenLiberty/openliberty.io#2319]
My employer uses ZScaler service to manage access to and results from external web sites.
ZScaler is blocking access to the "application.html" page for the following reason. I can access every other page I need, but the scan blocks this particular page. It blocks for 20 and 21 year versions of the page, too.

**ZScaler block.**
_Action_: deny
_Reason_: Trojan
_ReasonCode_: AV_AUTHENTIUM_VIRUS_SW_MW_BLOCK
_Blocked Category_: Other Information Technology
_URL_: https://openliberty.io/docs/21.0.0.10/reference/config/application.html

**Comment by mbroz2** [comment]
Hi @vickimfox,

There's not enough information here for us to be able to comment as to why ZScaler is blocking this page.  We'd need more information as to whether this false positive is because of some particular content on the page, an include, or just because the page file name is `application.html`.  

If there's more information you could provide us then we can see if there's something we can do to get around the ZScaler issue to avoid the false positive.  Otherwise, you'd probably need to request your admin to add an exception in ZScaler for this page.

**Comment by mbroz2** [comment]
@vickimfox I'm going to close this for now since there is no action we can take at the moment.  If you're still hitting this issue, please reopen this work item with the extra information that was requested.
