### ISSUE TITLE
Support multiple authors for blog posts

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#237]
There may be reasons for having more than one author on a blog post.  We currently only support one author per blog post in our `post.html`.

Tagging
@lauracowen 

**Update**:
Asciidoctor documentation on specifying multiple authors
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#document-header

**Comment by kinueng** [comment]
@lauracowen Let us know if you decide we need this issue

**Comment by lauracowen** [comment]
We definitely have cases where we'll have two or more authors on a blog post. I'm just not sure how critical it is in terms of priorities because I guess this would need a small amount of design work as well as implementation?

**Comment by lauracowen** [comment]
I'm going to close this issue for now and if it comes up again, I'll reopen it.

**Comment by kinueng** [comment]
@aguibert had asked about having multiple authors on a blog post.  I assume @aguibert has a current need for having this issue, so I reopened it.

**Comment by aguibert** [comment]
Thanks for reopening @kinueng. This would be really useful for most blog posts, so that devs can "share the spotlight" a bit. It's quite rare for a single developer to implement a piece of functionality. Normally it's 2-3 devs working on something and one of them writes a blog post on it.

My immediate use case is I'd like to write a blog about Liberty Bikes, but would like to add the other 3 members of my team as authors so it doesn't look like I wrote all of Liberty Bikes on my own. The alternative is that I could be a single author and just mention the rest of the Liberty Bikes team at the end of the post. It would be cool to get everyone's names and profile photos up at the top of the post though.

**Comment by mbroz2** [comment]
Tagged 'needs discussion' to go over blog etiquette/strategy regarding content authors (how to cite/credit authors/implementors of the underlying work the article is about).

**Comment by TreeHanh** [comment]
Here are the designs to show multiple authors. For the overview blog page we'll list out one author's name and "two others" or "three others" and so forth. Once they click on the blog post, it'll list out all the names. Desktop, tablet, and mobile versions are attached.

![blog_page_multipleauthors](https://user-images.githubusercontent.com/18586040/54052299-11323d00-41b2-11e9-9821-8c693b93fe9d.jpg)

![7_blog_post_desktop_top](https://user-images.githubusercontent.com/18586040/54052301-13949700-41b2-11e9-994d-a249864fbb78.jpg)

![9_blog_post_tablet](https://user-images.githubusercontent.com/18586040/54052306-155e5a80-41b2-11e9-8eb7-842c776cab23.jpg)

![10_blog_post_mobile](https://user-images.githubusercontent.com/18586040/54052313-17c0b480-41b2-11e9-955e-9b7a19289510.jpg)

**Comment by ellenwyllie** [comment]
It is now possible for blog posts to have multiple authors. I'm updating the README on the blogs repo with instructions for specifying additional authors.
