### ISSUE TITLE
Ensure guides are sorted by date

### ISSUE THREAD

**Issue by gindik** [OpenLiberty/openliberty.io#27]
The site implementation sorts guides by date (most recent first). This relies on the date-time being present in the guide front matter (or optionally variables in the case of adoc). Unfortunately this information appears to be missing. Note that by design the dates are not displayed on the site, they are only used for sorting purposes.

**Comment by kinueng** [comment]
I confirmed that Jekyll Front Matter `date` attribute is missing in all of the guides, which is causing the sorting to malfunction.

**Comment by kinueng** [comment]
I will work with the guides developers to find out what the ordering should be.

**Comment by kinueng** [comment]
My first attempt to sorting the guides was to add a `page-date` Asciidoctor attribute.  I didn't see any issues in my local Jekyll development environment through `jekyll s`.  However, I discovered that I cannot trust the development environment too much because `page-date` broke the `jekyll build` command.  Also, after recreating the build break error, I was reliability seeing the error in my `jekyll s` development environment.  I am not sure how I didn't see the error, but thats history not worth revisiting.

I did some research and found that there is a supported `jekyll-asciidoctor` attribute called `:revdate:`.  

> revdate (becomes date; value is converted to a DateTime object; posts only)

**Unfortunately**, this Asciidoctor attribute is for **posts only**.  By only posts, I assume only asciidocs that are found in the `_posts` folder.  I confirmed that adding the :revdate: attribute to our guides did nothing.

This leads me to using a custom attribute to do our sorting in `guides.html`.  Instead of doing `sort: 'date'`, we can use a custom attribute like `sort: 'releasedate'`.  In the guides, they would use an attribute `page-releasedate: 2017-11-10`.
