### ISSUE TITLE
RSS Feed: Blog posts that link to external site have broken URLs

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2719]
# Problem
There are some blog posts that are designed to link to an external domain. The problem with these specific links the `feed.xml` does not contain the external domain URL and contain an incorrect URL of `https://openliberty.io/blog/redirected.html`

You can see this problem on

# Feedly
https://feedly.com/i/subscription/feed/https%3A%2F%2Fopenliberty.io%2Ffeed.xml
<img width="699" alt="image" src="https://user-images.githubusercontent.com/31117513/173667614-bf36aa8b-9ae5-4268-8386-70dcb724e325.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/31117513/173667649-73024299-5ddf-4c9f-9ac9-6faf2c31824f.png">

# Newsblur
Not the empty content
![image](https://user-images.githubusercontent.com/31117513/173668703-79684885-97be-4199-aad4-fa4eec8eb84d.png)

Link goes to leads to...
![image](https://user-images.githubusercontent.com/31117513/173668585-ee38d85f-0338-4109-b44f-c881a3c6e62b.png)

Investigation is needed into the jekyll plugin `jekyll-feed` to see how to special handle these blog posts

**Comment by natalie-bernhard** [comment]
Currently, the jekyll-feed plugin does not allow for customization of the feed, so the permalink in the front matter of the .adoc is used as the post URL in the current feed rather than the redirect URL.  However, it is suspected that the permalink of the post cannot be changed to the redirect link because the permalink must point to an html file within the site to satisfy jekyll build reqs (which is why the redirected.html file was used as the permalink for external blogs).  This issue has not had any major effects on users at this point, so to avoid additional technical debt, closing this for now.
