### ISSUE TITLE
Some Jakarta feature pages are not properly ordering the feature versions

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/openliberty.io#2723]
In the Docs reference section, the JSON-P and JSON-B feature pages (and the related container features for each) are not resolving correctly. The FeaThey are defaulting to the older 1.0 version instead of 2.0 and the L to R ordering of the feature tabs is reversed. 

As a result, the pre-jakarta names are also showing in the TOC instead of the current feature names (JavaScript Object Notation... instead of Jakarta JSON...).
For example, see [JavaScript Object Notation Binding](https://openliberty.io/docs/latest/reference/feature/jsonb-1.0.html) and select any of the JSON features from the TOC. Note that the feature levels increase from left to right, which is the opposite of all the other features.

This is also a case with a number of other Jakarta features, including 

https://openliberty.io/docs/latest/reference/feature/websocket-1.1.html 
https://openliberty.io/docs/latest/reference/feature/mdb-3.2.html

Most likely other pages have the same problem, though not all. The pattern for the incorrect pages is not immediately clear.

**Comment by kinueng** [comment]
# Observations 
The file that handles the version picker for a specific feature is [parse_features_toc.py](https://github.com/OpenLiberty/openliberty.io/blob/prod/scripts/build/parse_features_toc.py). One of the responsibilities of this code is to consolidate each feature's versions together. For example, [`webProfile`](https://openliberty.io/docs/latest/reference/feature/webProfile.html) feature encompasses  `webProfile-9.1`, `webProfile-8.0`, and `webProfile-7.0`.

# Root Cause
The problem with the consolidation of each features' versions is how fragile the Python logic's assumptions are on the ordering of the features defined in [`feature-nav.doc`](https://raw.githubusercontent.com/OpenLiberty/docs-generated/vNext/modules/reference/partials/feature-nav.adoc). The script assumes that one feature's versions are listed from top-down starting with the lowest version to the highest version.

As you look at `webProfile`, the ordering is
```
  ** xref:feature/webProfile-9.1.adoc[Jakarta EE Web Profile]
  ** xref:feature/webProfile-7.0.adoc[Java EE Web Profile]
  ** xref:feature/webProfile-8.0.adoc[Java EE Web Profile]
```

Then the Python script will reverse the order by using https://github.com/OpenLiberty/openliberty.io/blob/daf09a6928e1ca915b7d58346148ab78cf5a87e0/scripts/build/parse_features_toc.py#L180-L181

So you get 8.0, 7.0, 9.1
https://openliberty.io/docs/latest/reference/feature/webProfile.html
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/31117513/176537058-29c1308a-8df4-4b22-bd5c-7e5af087d003.png">
