### ISSUE TITLE
"More downloads are on the way" at bottom of /start should only appear for an empty or partially rendered table

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2909]
Currently, "More downloads are on the way" at bottom of /start seems to always appear.  The image should only appear if the table is empty or partially rendered.
![image](https://user-images.githubusercontent.com/3076261/199239733-5828a7b6-9532-4a34-9b80-f9eaf8a8592f.png)

**Comment by natalie-bernhard** [comment]
I was able to write a fix for this where the current logic is as follows: if the ajax request for the builds data succeeds, the animation will be hidden, but if the request fails then it will render.  Just wanted to note this before moving forward, as the original issue mentions rendering the animation if the table is only partially rendered as well; since the number of releases in the table is not constant, I'm not sure how we would go about checking if the table is only partially rendered if the request succeeds.

**Comment by mbroz2** [comment]
I would check to make sure there's at least 24 releases rendered in the table, or if you want to do this in the same code as the ajax response, you could validate that runtime_releases has at least 24 elements in the array.  That's not quite the same since the response includes all releases and not just the ones we render, but I think it's fine.
