### ISSUE TITLE
New Guide Layout: Intro documents

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/openliberty.io#295]
For the new guide categories we plan on having an introductory document for the category.  This document will not be a guide itself but will appear as the first entry in the category.  The intro document will not have sample code associated with it, except for possible code snippets within the text.  Intro documents will have URLs similar to guides, like: https://openliberty.io/guides/intro-to-microprofile.html

This issue is to track how the Intro docs will be authored and stored in Git (i.e. will each intro document have its own repo like a guide?), and how the intro document will be published to the site.

For the associated design work, see https://github.com/OpenLiberty/guides-common/issues/112
For initial discussion on this topic, and creation of the Intro to MP doc, see https://github.com/OpenLiberty/guides-common/issues/107

**Comment by steven1046** [comment]
Having a separate repository for each intro document would be the most consistent approach with what we already have with each guide, although the intro documents would likely just be 1 asciidoc. It would be easier for the intro document authors to test these if they were in separate repositories like the guides since those are built using the master branch of each guide, and the authors can test changes using "draft-" at the beginning of the repo name before they are published.

The asciidocs for intro documents should contain most of the same front matter as the guides (dependent upon design for the page):
:projectid: rest-intro
:page-layout: intro-doc
:page-description: Learn how to create a REST service with JAX-RS, JSON-P, and Open Liberty.
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master

We will need a tag for the guide-category in order to place them in the right group on the guides page.
page-layout: guide should change to page-layout: intro-doc.

**Comment by megmulsy** [comment]
Template for the MicroProfile Intro is created 
PNG: https://ibm.box.com/s/g2b2whi1pwlxoe80kypgua6rqgevsx5g 
Redlines: https://ibm.box.com/s/2h5xsx4urjq041e5ectj9ftvhj5herut
NOTES: 

- Please take a look at how these pieces fit within the grid   Keep the left-hand nav open at all times, do not make it closeable like the other pages. 
- Images should either be left or right aligned, not centered. 
- Max size of image content is 916px across 
- Double check how this content works within the grid - if that's not viewable in the specs lemme know
- The ‘related guides’ would be the rest of the essentials from the  all guides page, Microprofile section.   
- Slight wording change in the left column at the bottom of the page (just for this guide)

**Comment by mbroz2** [comment]
Need to follow up to make sure these designs are still current (with the dual pane redesign), and that the content to populate these (Laura) is ready.

**Comment by kinueng** [comment]
We have published the first MicroProfile introduction documentation here
https://openliberty.io/docs/intro/microprofile.html
