### ISSUE TITLE
"Ask a question on Stack Overflow button" is not translated

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3007]
Create translated SVGs for the "Ask a question on Stack Overflow" button for blogs in other languages.  Right now, the button still shows up in English on all blog posts.  This could probably be done in Figma rather quickly.  New SVGs would need to be pushed to the blogs repo.

**Comment by kinueng** [comment]
This will be our first time handling images that are i18n sensitive. Currently all images are thrown into the same directory. We will need to separate non-English from the English images. So rather than having hardcoded absolute paths to images, the paths will need to pay attention to the language code in the URL.

**Comment by natalie-bernhard** [comment]
Images added via [this pull request](https://github.com/OpenLiberty/blogs/pull/2916).  File reorganization work is under Issue #3026 .
