### ISSUE TITLE
Wrong tags displaying on posts

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#3268]
The [blog posts listed under the `performance enhancements` tag](https://openliberty.io/blog/?search=performance_enhancements) don’t match those listed in the `performance enhancements` section of the [blog_tags.json file](https://github.com/OpenLiberty/blogs/blob/prod/blog_tags.json). Something seems to have gone wrong in the build of the blog index page.

The individual post page itself displays different (presumably correct?) tags.

For example, the [ARM64 (23..0.0.4 release) post](https://openliberty.io/blog/2023/05/02/23.0.0.4.html) displays the wrong tags on the index page but the (presumably) correct tags on the post page.

Index page:
![image](https://github.com/OpenLiberty/openliberty.io/assets/3322532/50978de5-cf4c-4b84-8eae-d5529fb6d6e8)

Post page:
![image](https://github.com/OpenLiberty/openliberty.io/assets/3322532/bafa20f4-084e-434c-bd18-8caa0f7a878f)

**Comment by amyreit** [comment]
After doing some debug, I've found that the tagging is broken because it assumes that there will only be one class of blog_post_title_link per each blog in the index and when a blog title has the secondary orange title in it, we for some reason generate a duplicate blog_post_title_link to add the continued_text span and then the logic to add the tags is broken because we index off the title and now the tag gets added to the blog below the one we are actually trying to add to. Need to investigate inside src/main/content/blog.html to see where the logic is going wrong and putting in a duplicate href section

**Comment by amyreit** [comment]
![Screenshot 2023-07-07 at 12 15 43 PM](https://github.com/OpenLiberty/openliberty.io/assets/24231238/44a52297-650c-4a12-890a-f91abb46e135)

**Comment by steven1046** [comment]
Should be fixed the the i18n blog tags #3324 work to remove the logic out of javascript and put it into the build process.
