### ISSUE TITLE
Prevent TOC from overlapping TOC menu accordion in guides single column view

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3305]
Prevent the guide TOC from rendering on top of the TOC accordion (`#mobile_toc_accordion`) when in mobile/single column view.  Instead, have the TOC move with the accordion, staying below it.

![Image](https://user-images.githubusercontent.com/84740311/254918257-b4330a54-870a-4404-9b36-9a15a3d3ce94.png)

**Comment by steven1046** [comment]
Try to address the toc being covered up in this issue if possible:
![image](https://github.com/OpenLiberty/openliberty.io/assets/6392944/f85a773b-743f-4752-881d-b0cc14c2e98a)

You can see the toc with the hamburger menu disappears because the code blocks have a higher z-index i think.




=======================================
This is what it looks like when it's normally visible:
![image](https://github.com/OpenLiberty/openliberty.io/assets/6392944/c1fd6235-9ebf-4b44-a379-090930d380bc)
