### ISSUE TITLE
Improve wording and links for "Add to an existing application"

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3449]
From @dmuelle :

we could break then out into 2 separate calls to action for each tool

- Ready to get started using Maven with Open Liberty? Try the [Building a web application with Maven] guide.
- Looking for information about Open Liberty Maven configuration, goals, and more? Check out the [Liberty Maven plugin documentation on GitHub].

- Ready to get started using Gradle with Open Liberty? Try the [Building a web application with Gradle] guide.
- Looking for information about Open Liberty Gradle configuration, tasks, and more? Check out the [Liberty Gradle plugin documentation on GitHub].

We might want to add some kind of intro statement for the plugin just under the Add to an existing application header. As it it now, we have this sentence between the two examples:

The plugin also needs to be applied in the build file in order to be utilized.

but we haven't said anything about a plugin or introduced it in any way. Something like

Open Liberty provides build plugins for Maven and Gradle that simplify the installation and operational control of the Liberty runtime and servers.

and i think this sentence could be improved

The plugin also needs to be applied in the build file in order to be utilized.
--->
You must also apply the plugin in the build file before you can use it:

**Comment by steven1046** [comment]
On the site meeting, we discussed that we should link to different parts of the github repos.
For Maven, link to the plugins section of the README (https://github.com/OpenLiberty/ci.maven/blob/main/README.md#plugins) because that README has more info and is more digestible to read.
For Gradle, link to https://github.com/OpenLiberty/ci.gradle/blob/main/README.md#plugin-configuration.
