### ISSUE TITLE
Make clicking PEM download file rather than showing the text in a new browser tab

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3457]
![Image](https://user-images.githubusercontent.com/31117513/225654145-37c0b770-ad9e-44b6-850c-4b1205bd377f.png)

Clicking this button leads to 

![Image](https://user-images.githubusercontent.com/31117513/225654262-f08d64f7-da86-4a4a-a8cd-3ee5b9741307.png)

---
We want this click to just download the file.

**Comment by natalie-bernhard** [comment]
After researching, we found that the work required to force a download does not seem to justify the improvement. However, Issue #3095 was opened in response to this in order to still make a UX improvement for the user by opening the window in a new tab instead of the same tab.  Closing this issue without a fix.
