### ISSUE TITLE
Testing Multipane (Creating a RESTful web service)

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#767]
- [ ] While the middle panel is in the `What you'll learn` section, the right panel shows code that is not mentioned until a later section. This might be confusing for the user because there is no explanation for the code they are seeing in the middle panel. Maybe if there is a blank right panel when there is no relevant code to be displayed that would be better.

- [x] In the `What you'll learn section` the URL and JSON object should not be elements that are copiable. Also in the `Creating the JAX-RS resource` section the @Path annotation section and HTTP get request should not be elements that are copiable. `Configuring the server` boot strap properties should not be copiable and the parts of the test code in the test section. 
<img width="622" alt="screen shot 2018-11-08 at 2 16 18 pm" src="https://user-images.githubusercontent.com/18709242/48221766-edc0c800-e360-11e8-8b52-de051e609a61.png">

- [ ] Is it possible to make the copy & paste button in the top right hand corner larger or more apparent like it is in the middle pane right now? 

- [ ] When the page is initially loaded, the Contents section has an [x] to collapse the left side, it is located on the upper right hand side of the section before you collapse it for the first time. When you expand the section again, the [x] is now located on the top left hand side of the panel. I'm not sure if it's intentional or not but it's slightly inconsistent. I also feel like [x] implies that we might not be able to get the contents section back so maybe an arrow < that shows that it can be expanded/put back would be more intuitive? 

**Initial**
<img width="436" alt="screen shot 2018-11-08 at 2 16 05 pm" src="https://user-images.githubusercontent.com/18709242/48221752-e8637d80-e360-11e8-8c3c-4dc15cc9e188.png">

**After collapsing and re-expanding**
<img width="408" alt="screen shot 2018-11-08 at 2 16 12 pm" src="https://user-images.githubusercontent.com/18709242/48221749-e7325080-e360-11e8-96af-404571a0f07f.png">

- [ ] The middle pane is smaller than the coding section before you collapse the contents column and it feels like the code is a more central part of what the user is looking at, even though it should be the guide. I think this issue was addressed previously that it's set by the characters per line of code. But I think the concern is that the focus seems to be directed at the code rather than the guide when the middle pane is smaller. 

- [ ] The contents section does not seem centered (left margin seems smaller than right margin)
<img width="308" alt="screen shot 2018-11-08 at 2 20 45 pm" src="https://user-images.githubusercontent.com/18709242/48222016-8c4d2900-e361-11e8-9368-7bf15c2d33dd.png">

- [ ] The guide section does not seem centered (left margin seems smaller than right margin)
<img width="757" alt="screen shot 2018-11-08 at 2 22 03 pm" src="https://user-images.githubusercontent.com/18709242/48222096-bb639a80-e361-11e8-93b4-347d6cea034a.png">

 - [x] The back ticks in code commands are showing up:
<img width="599" alt="screen shot 2018-11-09 at 12 13 52 pm" src="https://user-images.githubusercontent.com/18709242/48277573-14423a00-e419-11e8-9d2c-2ac3b34b9956.png">

**Comment by steven1046** [comment]
Hi Justine,

While the middle panel is in the What you'll learn section, the right panel shows code that is not mentioned until a later section. This might be confusing for the user because there is no explanation for the code they are seeing in the middle panel. Maybe if there is a blank right panel when there is no relevant code to be displayed that would be better.
This was part of the design.

Is it possible to make the copy & paste button in the top right hand corner larger or more apparent like it is in the middle pane right now?
@megmulsy do you think we could increase the size?

When the page it initially loaded, the Contents section has an [x] to collapse the left side, it is located on the upper right hand side of the section before you collapse it for the first time. When you expand the section again, the [x] is now located on the top left hand side of the panel. I'm not sure if it's intentional or not but it's slightly inconsistent. I also feel like [x] implies that we might not be able to get the contents section back so maybe an arrow < that shows that it can be expanded/put back would be more intuitive?
The table of contents will change behavior soon so when you hover near the left side of the page it will pop out and then close when you move your mouse away so the current implementation will change.

The middle pane is smaller than the coding section before you collapse the contents column and it feels like the code is a more central part of what the user is looking at, even though it should be the guide. I think this issue was addressed previously that it's set by the characters per line of code. But I think the concern is that the focus seems to be directed at the code rather than the guide when the middle pane is smaller.
The code column on the right is always a fixed size to keep the code in tact and not mess up the syntax when the page is resized/expanded. If the user wanted to make the guide section bigger they could decrease the zoom on their browser.

The contents section does not seem centered (left margin seems smaller than right margin)
The guide section does not seem centered (left margin seems smaller than right margin)
I'll look into this.

**Comment by justineechen** [comment]
I rearranged these issues into individual ones:
https://github.com/OpenLiberty/openliberty.io/issues/774
https://github.com/OpenLiberty/openliberty.io/issues/773
https://github.com/OpenLiberty/openliberty.io/issues/772
https://github.com/OpenLiberty/openliberty.io/issues/771
https://github.com/OpenLiberty/openliberty.io/issues/770
