### ISSUE TITLE
Switching spec versions in javadoc should keep you on the same location (if possible)

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/openliberty.io#785]
When I am browsing javadoc on openliberty.io, I frequently search for my package/class, then start looking at it and realize I'm looking at the wrong version (Java EE 7 instead of 8 or vice versa).

The version button up top is very convenient, but when we change versions it kicks the user out to the overall page and they have to repeat their search process.

For example:
1. go to https://openliberty.io/docs/ref/javaee/7/#class=javax/enterprise/concurrent/AbortedException.html&package=allclasses-frame.html
2. realize I want to look at the EE8 version, click the `Version: 8` button
3. get kicked out to: https://openliberty.io/docs/ref/javaee/8/
4. re-navigate to the target class

Instead, we should try to just replace the version in the URL but stay at the same doc page.  

There may be cases where this is not possible, e.g. looking at a new EE8 API, then select EE7 where the API doesn't exist.  For those situations, I think it would be appropriate to do any of:
A. kick the user out to the overall javadoc page of the selected version (current behavior)
B. give a 404 (shows the class doesn't exist at that version)
C. don't even display the button for versions where the API does not exist.  For example, when looking at https://openliberty.io/docs/ref/javaee/8/#class=javax/json/bind/Jsonb.html&package=allclasses-frame.html (a class new in EE8) don't show 7 as a version option

**Comment by ellenwyllie** [comment]
@cajaygle I've been working on this issue, but I'm not sure what we want to happen when the user tries to go to a version that doesn't exist for that particular API. I don't really like the idea of showing a 404 page because it might just seem like a bug. 

So I was thinking we could display a message that says that that version doesn't exist for that javadoc page when they try to click on it. Or we could gray out the version and make it so you can't click on if it doesn't exist.

And would we also need a way to get back to the home page of a version if we implement this?

**Comment by cajaygle** [comment]
I agree that a 404 page would not be good.  Also I don't think we should disable the version selector in the breadcrumb.  The selector applies to the Javadoc as a whole and I think it would be confusing if we disable elements depending on what page they are viewing.

The easiest option in this scenario would be to take them back to the All Packages / All Classes view if they were viewing a package/type that doesn't exist in a different version.

But I think the nicest option would be to present a message, so that the user knows the package/type doesn't exist.  Present the message in the content area, where the package/type would have been displayed.  The lefthand panes can be reset to All Packages / All Classes, which is all they need to navigate to something new.   In the center pane, the Package, Class, Tree, and Deprecated buttons at the top would be disabled.

Here's a mockup:
<img width="1122" alt="screen shot 2019-02-15 at 9 12 50 am" src="https://user-images.githubusercontent.com/27516391/52862040-2f9c9f80-3102-11e9-90ac-abe12f1f9c40.png">

If the URL for this were kept as https://openliberty.io/docs/ref/microprofile/1.2/#package=javax/enterprise/inject/literal/package-frame.html&class=javax/enterprise/inject/literal/package-summary.html it would allow them to switch back to a later version to see the package again.
