### ISSUE TITLE
Multiple source files with same names - High priority

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#815]
![image](https://user-images.githubusercontent.com/4803104/49238403-56ceb500-f3ce-11e8-8c8b-1adf0f6a0dd2.png)

Multiple tabs of the same names showed up in the source pane
- Shouldn't appear more than once if it is the same file
- If they are different files, need a way to identify them properly

https://qa-guides-multipane.mybluemix.net/guides/getting-started.html

**Comment by yeekangc** [comment]
@gkwan-ibm @justineechen

**Comment by steven1046** [comment]
@yeekangc Will we ever have the same file name in another section, but with more content than the previous section?

**Comment by lauracowen** [comment]
We try to avoid changing files (only create them). I think the only place we legitimately do it is maybe (IIRC?) in the Maven guide (and maybe Gradle?) which have incredibly long XML files, and in the recent Spring migration one which is all about *changing* an app.

I think it would get confusing though if there are multiple versions of the same file...(though I've not been through a guide with multiple tabs yet so maybe it's obvious which tab you're on in a given section of the guide?). Maybe this comes back to @steven1046 's question about whether all the tabs need to be displayed continuously or whether an updated file is just replaced with the updated version when necessary?

**Comment by justineechen** [comment]
@steven1046 There aren't multiple versions of the same file in the repository itself. So the content of the file will remain the same. Sometimes the guides will reference parts of the configuration files in later sections of the guide to describe the configuration for certain topics. 

In previous guides, there would be snippets that allow users to add onto an existing file but that was hard coded into the adoc. Switching to multipane, we only display the full /finish file on the right panel. 

The issue from this, I think is because the website picks up the "include" from each section and it will create a new file.. maybe there's a way for the website to detect if the file was already included in the right panel before adding it there? Also we need to add another include or else the hotspot won't know which file it's referring to.

**Comment by justineechen** [comment]
Also, in the getting-started issue with two `server.xml`s the second `server.xml` is the same as the first one but duplicated.
