### ISSUE TITLE
Twitter button not working due to special character in blog title

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#830]
## Problem
We are not handling the `'` character from the blog title correctly for the twitter button's JavaScript behavior.  Blog post https://openliberty.io/blog/2018/12/05/REST-Liberty-reactive-2018.html.  
We need to find a way to escape the '`' character

![image](https://user-images.githubusercontent.com/31117513/49541677-1d4bed00-f899-11e8-889f-a0454f5ba02f.png)

## Error
Uncaught SyntaxError: missing ) after argument list

**Comment by ellenwyllie** [comment]
I tried to resolve this issue and was able to do it by removing the encodeURIComponent function, but we are worried that removing this will break the encoding of other characters. EncodeURIComponent does not encode some special characters including apostrophes. 

Another way to fix this issue is to replace the apostrophe with '%27'. The problem with this is that you see "%27" in the tweet text.

The other option is to simply remove the apostrophe.

**Comment by aknguyen7** [comment]
the fix I dropped work locally but doesn't work in production
