### ISSUE TITLE
Request to remove "overview" topic after "Server commands"

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/openliberty.io#906]
For server commands here: https://openliberty.io/docs/ref/command/  Would you move move the "Overview" topic immediately below "Server commands"? Since "Server commands" is not a topic, it seems a little odd to have "Overview" above "Server commands" and the rest of the topics below "Server commands". - Thanks

**Comment by mbroz2** [comment]
The intent is for "Server Commands" to be the header for the items below, which are all server commands.  "Overview" is not a server command therefore it is above it.  The same is true for the Overview is Server Config (https://www.openliberty.io/docs/ref/config/)

One option would be to make the "Server Commands" header (and "Server Configuration" in the config docs) the actual Overview page.  Then we would remove the "Overview" above it and make those headers ("Server Commands" and "Server Configuration") clickable.

**Comment by TreeHanh** [comment]
We've decided to move the "overview" underneath the "Server Commands" and "Features" page. "Overview" will still be the first item highlighted when navigating to the page.

![overview config](https://user-images.githubusercontent.com/18586040/52864177-98d2e180-3107-11e9-91a1-63f33b4c16b5.png)

![overview features](https://user-images.githubusercontent.com/18586040/52864198-a1c3b300-3107-11e9-8012-bd2afe7580f6.png)

**Comment by cajaygle** [comment]
As Thuy-Hanh said, we discussed this and feel that keeping a separate Overview page but moving it below the header is the best option.  When they first come to the page, the Overview page will be selected so it'll be clear what it is.  Making the Server Command header the overview page makes it more obscure.

As part of this can we also add a Server Features header to the Features page for consistency.

**Comment by mbroz2** [comment]
Agreed on consistency and it's an easy change to make.  I will mention that I would have preferred something more like this instead:
![image](https://user-images.githubusercontent.com/3076261/52870965-a8a1f400-310e-11e9-91fe-bb55de26c399.png)
as it makes it clear that Overview is not one of the items under the header in the TOC (for example, Overview is not a name of a Liberty Feature).  With the above proposed designs, the only distinguishable difference in "Overview" vs everything else in the TOC is that it doesn't follow alphabetical order, but a user would first have to notice (skim the table) to see that that is the case.  Furthermore, if the user wanted to go back to Overview, they may look around "O" for it since the rest of the table is organized.  Neither one is a big problem and could be lessened even further with a slight css change to further differentiate "Overview" from the other items in the table, or by making the Overview and Header one item like in the image above.

**Comment by cajaygle** [comment]
Neither Melissa, Thuy-Hanh, nor I feel that anyone will be confused having Overview as the first item in the list.  As I mentioned, when they come to the page it will be selected and displayed.  No one's going to be looking in the O's for the overview doc.  Having the header merged with overview like you have is visually cluttered.

**Comment by mbroz2** [comment]
Moving this out of icebox to backlog, see Thuy-Hanh's [comment](https://github.com/OpenLiberty/openliberty.io/issues/906#issuecomment-464077983 ) for the design.

**Comment by TreeHanh** [comment]
@ellenwyllie We've decided to go forward with making the "overview" all caps and size 12 font. 

![Config_Example_](https://user-images.githubusercontent.com/18586040/54051269-5dc84900-41af-11e9-8d41-c3b407c26774.jpg)
