### ISSUE TITLE
Safari caching hides the tabs of the files - Medium Priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#941]
<img width="1679" alt="screen shot 2019-01-31 at 3 39 32 pm" src="https://user-images.githubusercontent.com/18709242/52083826-88026780-256e-11e9-9661-3f7d0925bcf5.png">

**Comment by steven1046** [comment]
Intermittent bug

**Comment by steven1046** [comment]
This is hard to recreate, and I think it is a safari only bug on any doc header page on the website since I think i've seen it before. Sometimes the header has css jumbled and covers up the rest of the page so you can't click on anything covered up by the doc header. Closing until we see it happen again.

**Comment by kinueng** [comment]
I was not able to recreate this problem with Safari
