### ISSUE TITLE
[Static guides] Difficult maintenance for current hotspot implementation - High priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#979]
Currently, we use [hotspot=line numbers] which detects the line numbers of files **without** any tags we have included in the file. This means that copyrights or any tags that hide/show code won't be counted in the line numbers. So when we write the guide, we need to go through each file and temporarily delete these tags in order to get the correct hotspot line numbers. This makes the process a bit tedious for all users who contribute to guides.

Another issue we may have in the future, is that any code changes we make on the files will alter all the hotspot line numbers in the README for the guide. 

Note: In our static guides we used to use tags to section out parts of code that we want to highlight to users without worrying about specific line numbers but it seems like that may not be a possible solution for multipane guides.

<img width="831" alt="screen shot 2019-02-08 at 11 39 45 am" src="https://user-images.githubusercontent.com/18709242/52491962-4721d880-2b96-11e9-9734-47f246822842.png">
@gkwan-ibm

**Comment by steven1046** [comment]
We will have to look into writing an extension for asciidoc or similar in order to read the tags from the java/xml files to map to hotspots.

**Comment by gkwan-ibm** [comment]
I raise this issue as a high priority issue. When we are preparing the PR for multipane, the master changes need to be applied on the multipane branch. The changes for sources affect the line numbers of the hotspots. We need to manually fix the README.adoc and re-test the guides again. The current hotspot support by using line-numbers is really hard to maintain for any change.

I tagged @mbroz2 and @yeekangc for your attention

**Comment by yeekangc** [comment]
Yes, this is a high priority and serious issue.  Maintenance is difficult and arguably a nightmare if we need to maintain line numbers.  It won't scale and will be difficult for any contributor.  We have quite a few guides to maintain already and the list will only grow.

@mbroz2 @kinueng @steven1046, appreciate your attention and help with this problem.

**Comment by steven1046** [comment]
@justineechen @gkwan-ibm @yeekangc Currently some of the hotspots specify lines that aren't currently a tag name correct? Would you be willing to go back to each asciidoc and surround the lines for every hotspot with a tag if we did this? We would also need some way to stage the changes like a dev branch since adding tags around hotspots would change the line numbers and affect production.

**Comment by gkwan-ibm** [comment]
@steven1046 Did you have a solution? 

We did not remove the tags from the sources. We only need to switch to use tag name instead of line numbers. So, let us coordinate how to make that change: e.g. we will create a new branch `hotspots`, and there is a test guides site to use that branch.

**Comment by yeekangc** [comment]
Yes, we will need to stage the changes properly.  Should align with our plan to beef up our infrastructure.  I can see a dedicated branch and test site for such changes to avoid production outage and any out-of-sync window.

**Comment by steven1046** [comment]
I see that the original tag names were not removed, however there are hotspots that refer to single lines and lines other than just whats inside of the tags. For example in the JWT guide, there is a hotspot referring to just `<feature>mpJwt-1.1</feature>` but no tag surrounding that line only. So there would have to be further work in the asciidocs once this is enabled. Unless we want to support both line numbers and tag names.

**Comment by gkwan-ibm** [comment]
Because hotspots is new. the guides take this advantage to highlight the specific content in the multipane conversion which single pane could not. We understand that we need to add tags for those hotspots. Ideally, it will be great if hotspots can support both syntax-es and if the line # counting is same as current, so that we can convert back to use tags gradually. Anyway, eventually, we will use tags only. 

In addition, I am concerning how to support multiple `[hotspot=32 hotspot=38]`&#96;`arquillian-managed.war`&#96;

In following example to highlight line1 and line4 together, 
1. do `[hotspot=t1 hotspot=t2]`&#96;`arquillian-managed.war`&#96;
```
// tag::t1
line1
// end::t1
line2
line3
// tag::t2
line4
// end::t2
```
2. or do `[hotspot=t1]`&#96;`arquillian-managed.war`&#96;
```
// tag::t1
line1
// end::t1
line2
line3
// tag::t1
line4
// end::t1
```

**Comment by steven1046** [comment]
The work is close to done, I have set up the http://hotspots-openlibertyio.mybluemix.net environment to use the `hotspots` branch of openliberty.io and the `hotspots` branch of each guide. Both line numbers and tag names will be supported to hotspot some text. The line numbers will now work to be the exact line in the included file, meaning no math is required. I am still testing some more and then I will schedule a meeting to discuss it.
